repos:
  # Terraform formatting
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.83.5
    hooks:
      - id: terraform_fmt
        args:
          - --args=-check
          - --args=-diff

  # General file fixes
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      # Ensure files end with a newline
      - id: end-of-file-fixer
      # Remove trailing whitespace
      - id: trailing-whitespace
      # Check yaml files
      - id: check-yaml
      # Check json files
      - id: check-json
      # Check for merge conflicts
      - id: check-merge-conflict
      # Check for files that would conflict on case-insensitive filesystems
      - id: check-case-conflict